# Data upload

In [23]:
#to mount Google Drive on Google Colab
from google.colab import drive
drive.mount('/content/drive')

# JSON file download
! mkdir -p ~/.kaggle
! cp /content/drive/MyDrive/Colab/0_archive/kaggle.json ~/.kaggle
! chmod 600 ~/.kaggle/kaggle.json

# to download dataset from Kaggle
!kaggle competitions download -c titanic -p "/content/drive/MyDrive/Colab/3_machine_learning/Practice/Titanic_Machine_Learning_from_Disaster"
# Please check the file pathway in your Google Colab

# path to the directory containing the zip file
import zipfile
import os
titanic= "/content/drive/MyDrive/Colab/3_machine_learning/Practice/Titanic_Machine_Learning_from_Disaster/titanic.zip"
# Please check the file pathway in your Google Colab

# Path to the directory where you want to extract the contents
titanic_path = "/content/drive/MyDrive/Colab/3_machine_learning/Practice/Titanic_Machine_Learning_from_Disaster"
# Please check the file pathway in your Google Colab

# Unzip the file
with zipfile.ZipFile(titanic, 'r') as zip_ref:
    zip_ref.extractall(titanic_path)

# List the contents of the extracted directory
extracted_titanic = os.listdir(titanic_path)
print("Extracted files:", extracted_titanic)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
titanic.zip: Skipping, found more recently modified local copy (use --force to force download)
Extracted files: ['ML_practice', 'titanic.zip', 'gender_submission.csv', 'test.csv', 'train.csv']

In [26]:
import pandas as pd
import numpy as np

train=pd.read_csv("/content/drive/MyDrive/Colab/3_machine_learning/Practice/Titanic_Machine_Learning_from_Disaster/train.csv")
test=pd.read_csv("/content/drive/MyDrive/Colab/3_machine_learning/Practice/Titanic_Machine_Learning_from_Disaster/test.csv")

In [27]:
train.info()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [28]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# Null data

In [30]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

# Fill blanks

In [32]:
train_test=[train, test]

In [33]:
for dataset in train_test: dataset["Title"]= dataset["Name"].str.extract("([\w]+)\.", expand=False)

In [34]:
train['Title'].value_counts()

Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Mlle          2
Major         2
Col           2
Countess      1
Capt          1
Ms            1
Sir           1
Lady          1
Mme           1
Don           1
Jonkheer      1
Name: Title, dtype: int64

In [35]:
test['Title'].value_counts()

Mr        240
Miss       78
Mrs        72
Master     21
Col         2
Rev         2
Ms          1
Dr          1
Dona        1
Name: Title, dtype: int64

In [36]:
Title_mapping= {"Mr": 0, "Miss":1, "Mrs":2, "Master":3, "Dr":4, "Rev":5,"Mlle":6, "Major":7,
                "Col":8,"Countess":9, "Capt":10, "Ms":11, "Sir":11, "Lady":12, "Mme":13, "Don":14,
                "Jonkheer":15, "Dona":16, "Dr":17}
for dataset in train_test:
    dataset["Title"]=dataset["Title"].map(Title_mapping)

In [37]:
train["Title"].unique()

array([ 0,  2,  1,  3, 14,  5, 17, 13, 11,  7, 12,  6,  8, 10,  9, 15])

In [38]:
test["Title"].unique()

array([ 0,  2,  1,  3, 11,  8,  5, 17, 16])

In [39]:
for dataset in train_test: dataset["Title_group"]= dataset["Name"].str.extract("([\w]+)\.", expand=False)

for dataset in train_test:
    dataset['Title_group'] = dataset['Title_group'].apply(lambda x: 0 if x=="Mr" else 1 if x=="Miss" else 2 if x=="Mrs" else 3 if x=="Master" else 4)

In [40]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Title_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,0

In [41]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Title_group
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,2,2
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,2

In [42]:
for dataset in train_test: dataset['Age'].fillna(dataset.groupby("Title_group")["Age"].transform("median"), inplace=True)

In [43]:
for dataset in train_test: dataset["Fare"].fillna(dataset.groupby("Pclass")["Fare"].transform("median"), inplace=True)

# Replace categorical values to binary

In [45]:
# Sex
sex_mapping = {"male": 0, "female":1}
for dataset in train_test:
    dataset["Sex"]=dataset["Sex"].map(sex_mapping)

In [46]:
# Embarked
dataset["Embarked"].unique()

array(['Q', 'S', 'C'], dtype=object)

In [47]:
Embarked_mapping = {"C":0, "Q":1, "S":2}
for dataset in train_test:
    dataset["Embarked"]=dataset["Embarked"].map(Embarked_mapping)

In [48]:
for dataset in train_test: dataset['Embarked'].fillna(dataset.groupby("Title_group")["Embarked"].transform("median"), inplace=True)

# Specific grouping

In [49]:
for dataset in train_test:
    dataset["Agebin"]= pd.cut(dataset["Age"], 5, labels= [0,1,2,3,4])

In [ ]:
for dataset in train_test:
    dataset["Farebin"]= pd.cut(dataset["Fare"], 4, labels= [0,1,2,3])

# Create the answer sheet and final train data

In [50]:
drop_column=["Name", "Age", "SibSp","Parch","Ticket","Fare","Cabin", "Title"]

for dataset in train_test:
    dataset=dataset.drop(drop_column, axis=1, inplace=True)

In [51]:
target= train["Survived"]
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [52]:
drop_column2=["PassengerId", "Survived"]
train_data=train.drop(drop_column2, axis=1)
train_data

     Pclass  Sex  Embarked  Title_group Agebin
0         3    0       2.0            0      1
1         1    1       0.0            2      2
2         3    1       2.0            1      1
3         1    1       2.0            2      2
4         3    0       2.0            0      2
..      ...  ...       ...          ...    ...
886       2    0       2.0            4      1
887       1    1       2.0            1      1
888       3    1       2.0            1      1
889       1    0       0.0            0      1
890       3    0       1.0            0      1

[891 rows x 5 columns]

# Testing the Models

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [54]:
# Initialize Logistic Regression model
clf1 = LogisticRegression()

# Fit the model on the training data
clf1.fit(train_data, target)

# Check accuracy on the training data
accuracy = clf1.score(train_data, target)
print("Accuracy:", accuracy)

Accuracy: 0.792368125701459

In [55]:
## Initialize Random forest model
clf2 = RandomForestClassifier()

# Fit the model on the training data
clf2.fit(train_data, target)

# Check accuracy on the training data
accuracy = clf2.score(train_data, target)
print("Accuracy:", accuracy)

Accuracy: 0.8406285072951739

In [56]:
# Initialize Gaussian model
clf3 = GaussianNB()

# Fit the model on the training data
clf3.fit(train_data, target)

# Check accuracy on the training data
accuracy = clf3.score(train_data, target)
print("Accuracy:", accuracy)

Accuracy: 0.7789001122334456

In [57]:
# Initialize Decision Tree model
clf4 = DecisionTreeClassifier()

# Fit the model on the training data
clf4.fit(train_data, target)

# Check accuracy on the training data
accuracy = clf4.score(train_data, target)
print("Accuracy:", accuracy)

Accuracy: 0.8406285072951739

In [58]:
# Initialize SVC model
clf5 = SVC()

# Fit the model on the training data
clf5.fit(train_data, target)

# Check accuracy on the training data
accuracy = clf5.score(train_data, target)
print("Accuracy:", accuracy)

Accuracy: 0.8226711560044894

# Create the final test data

In [59]:
drop_column3=["PassengerId"]
test_data=test.drop(drop_column3, axis=1)

# Prediction

In [60]:
predict= clf2.predict(test_data)

In [61]:
submission = pd.DataFrame({
    'PassengerId' : test['PassengerId'],
    'Survived' : predict})

In [62]:
submission.to_csv('submission.csv', index=False)

submission = pd.read_csv("submission.csv")
submission.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         0

In [63]:
import shutil
shutil.copy("submission.csv", "/content/drive/My Drive/submission.csv")

'/content/drive/My Drive/submission.csv'